### ISSUE TITLE
Tasty dependency breaks build on Nixpkgs 21.05

### ISSUE THREAD

**Issue by CMCDragonkai** [awakesecurity/proto3-suite#154]
The current tasty dependency on Nixpkgs 21.05 is 1.4.1. The proto3-suite still requires 1.3.

Is there a way to loosen this dependency?

**Comment by CMCDragonkai** [comment]
Cool this needs to be pushed to hackage too so that nixpkgs can scrape it.

**Comment by Gabriel439** [comment]
@CMCDragonkai: I published a matching revision to Hackage
