### ISSUE TITLE
Preserve `--out` directory casing in `compile-proto-file`

### ISSUE THREAD

**Issue by riz0id** [awakesecurity/proto3-suite#182]
The ambient directory of `--proto` file given to `compile-proto-file` determines the module names of generated `*.hs` files. However, `compile-proto-file` applies [casing changes to the generated module name](https://github.com/awakesecurity/proto3-suite/blob/7af7d76dcf9cc71ddada3aa4a38abf46f65550ca/src/Proto3/Suite/DotProto/Generate.hs#L80) so that the first letter is capitalized and all remaining letters are lowercased. This causes the following:

```sh
compile-proto-file --includeDir proto/ --proto HTTP/mybuffer.proto --out gen 
``` 

To produce a module named `Http.Mybuffer`. I would expect that `compile-proto-file` would preserve the casing here and instead generate a module `HTTP.Mybuffer`.

**Comment by j6carey** [comment]
For reference, here is how names are handled for C++ code generation using `protoc`:
```
$ protoc --cpp_out gen SuB/MyFile.proto 
/$ ls gen/
SuB
/$ ls gen/SuB/
MyFile.pb.cc  MyFile.pb.h
$ 
```
