### ISSUE TITLE
Unable to build source dist of proto3-suite

### ISSUE THREAD

**Issue by morucci** [awakesecurity/proto3-suite#198]
Hi,

It seems that cabal sdist fails on the project:

```
[nix-shell:~/git/github.com/proto3-suite]$ cabal sdist
cabal: sdist of proto3-suite-0.5.0: Error: Could not find module: TestProto
with any suffix:
["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the
module is autogenerated it should be added to 'autogen-modules'.
```

This might cause trouble when using source-repository-package in cabal.project.

**Comment by tmcgilchrist** [comment]
This was fixed with https://github.com/awakesecurity/proto3-suite/pull/185 which added `autogen-modules` to the cabal file.
