### ISSUE TITLE
Distinct proto3 identifiers map to the same Haskell identifier

### ISSUE THREAD

**Issue by j6carey** [awakesecurity/proto3-suite#22]
The underscores get removed; see the example `.proto` file (renamed to `.txt` to please GitHub):

[test.proto.txt](https://github.com/awakesecurity/proto3-suite/files/1209536/test.proto.txt)

**Comment by vincenthz** [comment]
looks like `dotProtoEnumD` is camel casing all the constructors with:

```
                 sequence [ (i,) <$> (prefixedConName enumName =<< ...
```

which call `typeLikeName`, which call `camelCase` and then transform sequence of (non leading) `_ alpha` into `upper(alpha)`.

I can think of 2 ways to fix, either looking for duplicate and finding a backup name for a duplicate, or finding a name format that conserve `_`
