### ISSUE TITLE
Ensure desired CG rendering of fixed scalar types

### ISSUE THREAD

**Issue by intractable** [awakesecurity/proto3-suite#30]
In generated Haskell modules, we currently render record field types corresponding to protobuf message fields without any newtype wrapping, deferring necessary un/wrapping to the message's codec implementation. E.g., a field member for a nested message is rendered as the underlying `Maybe` type instead its contextually-correct `Nested` newtype wrapper.

The exception to this is the rendering for the fixed scalar types: `fixed32`, `sfixed32`, `fixed64`, and `sfixed64`. E.g., a `fixed32` field is currently rendered as `Fixed Word32`, in a data structure exposed to the consumer of the generated code – something we'd like to avoid.

The task here is to investigate whether or not this asymmetry is for some particular purpose, or if it is merely an historical implementation artifact that. If the former, let's document the snowflake, and if the latter (which is most likely), let's fix it.

**Comment by Gabriel439** [comment]
I'm pretty sure that this is a legacy of generating `.proto` from Haskell and is not necessary for generating Haskell from `.proto`

**Comment by intractable** [comment]
Ah, that makes sense. Thanks. Will leave this open so I remember to drop the `Fixed` wrapper.

**Comment by themattchan** [comment]
Fixed in #92
