### ISSUE TITLE
Natural is no longer an instance of Arbitrary on QuickCheck >= 2.10

### ISSUE THREAD

**Issue by ryota-ka** [awakesecurity/proto3-suite#66]
In the following line, it is expected that `Natural` is an instance of `Arbitrary` class, but since QuickCheck 2.10, the instance has been removed.
https://github.com/awakesecurity/proto3-suite/blob/master/src/Proto3/Suite/DotProto/AST.hs#L397

http://hackage.haskell.org/package/QuickCheck/changelog

> 	* Some Arbitrary instances have been removed: NonEmpty, Natural.
	  This is because they resulted in a lot of extra dependencies.
	  You can now find them in the quickcheck-instances package.
	  Alternatively, use the NonEmptyList and NonNegative modifiers.

We can depend on [`quickcheck-instances`](http://hackage.haskell.org/package/quickcheck-instances) package or simply make it an instance with [`arbitrarySizedNatural`](http://hackage.haskell.org/package/QuickCheck-2.11.3/docs/Test-QuickCheck-Arbitrary.html#v:arbitrarySizedNatural).

**Comment by ryota-ka** [comment]
I've forked this repo and solved the issue, so I can send a PR if you wish.

https://github.com/herp-inc/proto3-suite/commit/00b572807122e34fbb168bbda023aa12e0211c57

**Comment by Gabriel439** [comment]
@ryota-ka: I think the most reliable long-term solution is to depend on `quickcheck-instances` and specify a lower bound of `QuickCheck >= 2.10`.  I can put up a pull request for that soon
