### ISSUE TITLE
Add to Hackage/Stackage

### ISSUE THREAD

**Issue by ndmitchell** [awakesecurity/proto3-suite#71]
Any idea why these aren't released on Hackage/Stackage?

**Comment by Gabriel439** [comment]
I'll consolidate the discussion on https://github.com/awakesecurity/gRPC-haskell/issues/65

**Comment by sighingnow** [comment]
Hi @Gabriel439,

Seems that the package `proto3-suite`, `proto3-wire` and `grpc-haskell` on hackage haven't been updated for several release cycle. Any ideas why the new releases are not published on hackage?

Thanks!

**Comment by Gabriel439** [comment]
@sighingnow: I believe `proto3-wire` doesn't need an update since the only change since the last release was to make a revision to accept newer versions of `tasty`.  However, I will cut a new release for `proto3-suite` and `grpc-haskell`

**Comment by sighingnow** [comment]
> @sighingnow: I believe `proto3-wire` doesn't need an update since the only change since the last release was to make a revision to accept newer versions of `tasty`. However, I will cut a new release for `proto3-suite` and `grpc-haskell`

Thanks @Gabriel439.

**Comment by Gabriel439** [comment]
The reason for the delay in uploading these packages is because #138 caused issues with uploading `proto3-suite` to Hackage, which I'm in the process of fixing.  See https://github.com/haskell/cabal/issues/7348 for more details

**Comment by Gabriel439** [comment]
Alright, I just uploaded the latest versions of `proto3-wire` / `proto3-suite` / `gRPC-haskell`

**Comment by CMCDragonkai** [comment]
This issue can be closed.
