### ISSUE TITLE
Map types should allow non-Prim value types

### ISSUE THREAD

**Issue by joshsh** [awakesecurity/proto3-suite#83]
In [AST.hs](https://github.com/awakesecurity/proto3-suite/blob/master/src/Proto3/Suite/DotProto/AST.hs), we have:

```
data DotProtoType
  = Prim           DotProtoPrimType
  | Optional       DotProtoPrimType
  | Repeated       DotProtoPrimType
  | NestedRepeated DotProtoPrimType
  | Map            DotProtoPrimType DotProtoPrimType
  deriving (Show, Eq)
```

The `Map` constructor here is not consistent with the [Proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#maps), which states that "The value_type can be any type except another map". Accordingly, the constructor should be:

```
Map            DotProtoPrimType DotProtoType
```

...perhaps with an exception thrown if the provided value type is a map.

**Comment by themattchan** [comment]
This is not what the proto3 reference implementation actually does. If you try to compile, for example,

```
message Foo {...}
message MyMap {
  map<int32, repeated Foo> blah = 1;
}
```

using the python implementation, it will barf when parsing the `repeated` keyword. So what the spec really means is the value type can be any other _base type or message type_, which is what a `DotProtoPrimType` is.

**Comment by joshsh** [comment]
@themattchan that may be the behavior of the reference implementation, but at Uber we have interpreted the spec literally, permitting repeated values. This has been necessary for symmetry with Thrift.

I patched proto3 to support repeated map values at the AST and parser level. Let me know if you are interested in this patch as a PR.

**Comment by themattchan** [comment]
Sure, a PR is very welcome.
